import type { NextPage } from 'next'
import Head from 'next/head'
import Task from '../src/components/Task'
import Image from 'next/image'


const Home: NextPage = () => {
  return (
    <div className="p-5 sm:p-10 bg-gray-700 min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="sm:container sm:mx-auto">
        <Image width="100" height="30" alt="Zarego" src="/images/zarego.png"></Image>
        <Task />
      </main>
    </div>
  )
}

export default Home
